# Generated by Django 5.0.12 on 2025-04-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noControl', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=10)),
                ('claveCarrera', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('fechaInscripcion', models.DateField()),
                ('horaInscripcion', models.TimeField()),
                ('titulo', models.CharField(max_length=200)),
                ('noConsecutivo', models.CharField(max_length=50)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creditosAprobados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
