# Generated by Django 5.0.12 on 2025-04-07 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0002_remove_constancia_horainscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='horaInscripcion',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constancia',
            name='fechaInscripcion',
            field=models.DateField(),
        ),
    ]
